import ColorTypes as CT
import Colors
import FixedPointNumbers as FPN

struct BinaryTransparentColor{C}
    color::C
end

const COLORS = Dict{Symbol, BinaryTransparentColor{CT.RGBA{FPN.N0f8}}}()

COLORS[:BACKGROUND] = BinaryTransparentColor(CT.RGBA{FPN.N0f8}((Colors.color_names["lightgray"] ./ 255)...,))
COLORS[:BORDER] = BinaryTransparentColor(CT.RGBA{FPN.N0f8}((Colors.color_names["black"] ./ 255)...,))
COLORS[:TEXT] = BinaryTransparentColor(CT.RGBA{FPN.N0f8}((Colors.color_names["black"] ./ 255)...,))
# COLORS[:INDICATOR] = BinaryTransparentColor(CT.RGBA{FPN.N0f8}((Colors.color_names["black"] ./ 255)...,))
COLORS[:INDICATOR] = BinaryTransparentColor(CT.RGBA{FPN.N0f8}((Colors.color_names["black"] ./ 255)..., 0.5))

# Button
COLORS[:BUTTON_BACKGROUND_NEUTRAL] = BinaryTransparentColor(CT.RGBA{FPN.N0f8}((Colors.color_names["gray69"] ./ 255)...,))
COLORS[:BUTTON_BACKGROUND_HOT] = BinaryTransparentColor(CT.RGBA{FPN.N0f8}((Colors.color_names["gray75"] ./ 255)...,))
COLORS[:BUTTON_BACKGROUND_ACTIVE] = BinaryTransparentColor(CT.RGBA{FPN.N0f8}((Colors.color_names["gray75"] ./ 255)...,))

COLORS[:BUTTON_BORDER_NEUTRAL] = COLORS[:BORDER]
COLORS[:BUTTON_BORDER_HOT] = COLORS[:BORDER]
COLORS[:BUTTON_BORDER_ACTIVE] = COLORS[:BORDER]

COLORS[:BUTTON_TEXT_NEUTRAL] = COLORS[:TEXT]
COLORS[:BUTTON_TEXT_HOT] = COLORS[:TEXT]
COLORS[:BUTTON_TEXT_ACTIVE] = COLORS[:TEXT]

# TextBox
COLORS[:TEXT_BOX_BACKGROUND_NEUTRAL] = BinaryTransparentColor(CT.RGBA{FPN.N0f8}((Colors.color_names["white"] ./ 255)...,))
COLORS[:TEXT_BOX_BACKGROUND_HOT] = BinaryTransparentColor(CT.RGBA{FPN.N0f8}((Colors.color_names["white"] ./ 255)...,))
COLORS[:TEXT_BOX_BACKGROUND_ACTIVE] = BinaryTransparentColor(CT.RGBA{FPN.N0f8}((Colors.color_names["white"] ./ 255)...,))

COLORS[:TEXT_BOX_BORDER_NEUTRAL] = COLORS[:BORDER]
COLORS[:TEXT_BOX_BORDER_HOT] = COLORS[:BORDER]
COLORS[:TEXT_BOX_BORDER_ACTIVE] = COLORS[:BORDER]

COLORS[:TEXT_BOX_TEXT_NEUTRAL] = COLORS[:TEXT]
COLORS[:TEXT_BOX_TEXT_HOT] = COLORS[:TEXT]
COLORS[:TEXT_BOX_TEXT_ACTIVE] = COLORS[:TEXT]

# Text
COLORS[:TEXT_BACKGROUND_NEUTRAL] = COLORS[:BACKGROUND]
COLORS[:TEXT_BACKGROUND_HOT] = COLORS[:BACKGROUND]
COLORS[:TEXT_BACKGROUND_ACTIVE] = COLORS[:BACKGROUND]

COLORS[:TEXT_BORDER_NEUTRAL] = COLORS[:BACKGROUND]
COLORS[:TEXT_BORDER_HOT] = COLORS[:BACKGROUND]
COLORS[:TEXT_BORDER_ACTIVE] = COLORS[:BACKGROUND]

COLORS[:TEXT_TEXT_NEUTRAL] = COLORS[:TEXT]
COLORS[:TEXT_TEXT_HOT] = COLORS[:TEXT]
COLORS[:TEXT_TEXT_ACTIVE] = COLORS[:TEXT]

# CheckBox
COLORS[:CHECK_BOX_BACKGROUND_NEUTRAL] = COLORS[:BACKGROUND]
COLORS[:CHECK_BOX_BACKGROUND_HOT] = COLORS[:BACKGROUND]
COLORS[:CHECK_BOX_BACKGROUND_ACTIVE] = COLORS[:BACKGROUND]

COLORS[:CHECK_BOX_BORDER_NEUTRAL] = COLORS[:BACKGROUND]
COLORS[:CHECK_BOX_BORDER_HOT] = COLORS[:BACKGROUND]
COLORS[:CHECK_BOX_BORDER_ACTIVE] = COLORS[:BACKGROUND]

COLORS[:CHECK_BOX_TEXT_NEUTRAL] = COLORS[:TEXT]
COLORS[:CHECK_BOX_TEXT_HOT] = COLORS[:TEXT]
COLORS[:CHECK_BOX_TEXT_ACTIVE] = COLORS[:TEXT]

COLORS[:CHECK_BOX_INDICATOR_NEUTRAL] = COLORS[:INDICATOR]
COLORS[:CHECK_BOX_INDICATOR_HOT] = COLORS[:INDICATOR]
COLORS[:CHECK_BOX_INDICATOR_ACTIVE] = COLORS[:INDICATOR]

# RadioButton
COLORS[:RADIO_BUTTON_BACKGROUND_NEUTRAL] = COLORS[:BACKGROUND]
COLORS[:RADIO_BUTTON_BACKGROUND_HOT] = COLORS[:BACKGROUND]
COLORS[:RADIO_BUTTON_BACKGROUND_ACTIVE] = COLORS[:BACKGROUND]

COLORS[:RADIO_BUTTON_BORDER_NEUTRAL] = COLORS[:BACKGROUND]
COLORS[:RADIO_BUTTON_BORDER_HOT] = COLORS[:BACKGROUND]
COLORS[:RADIO_BUTTON_BORDER_ACTIVE] = COLORS[:BACKGROUND]

COLORS[:RADIO_BUTTON_TEXT_NEUTRAL] = COLORS[:TEXT]
COLORS[:RADIO_BUTTON_TEXT_HOT] = COLORS[:TEXT]
COLORS[:RADIO_BUTTON_TEXT_ACTIVE] = COLORS[:TEXT]

COLORS[:RADIO_BUTTON_INDICATOR_NEUTRAL] = COLORS[:INDICATOR]
COLORS[:RADIO_BUTTON_INDICATOR_HOT] = COLORS[:INDICATOR]
COLORS[:RADIO_BUTTON_INDICATOR_ACTIVE] = COLORS[:INDICATOR]

# DropDown
COLORS[:DROP_DOWN_BACKGROUND_NEUTRAL] = COLORS[:BACKGROUND]
COLORS[:DROP_DOWN_BACKGROUND_HOT] = COLORS[:BACKGROUND]
COLORS[:DROP_DOWN_BACKGROUND_ACTIVE] = COLORS[:BACKGROUND]

COLORS[:DROP_DOWN_BORDER_NEUTRAL] = COLORS[:BACKGROUND]
COLORS[:DROP_DOWN_BORDER_HOT] = COLORS[:BACKGROUND]
COLORS[:DROP_DOWN_BORDER_ACTIVE] = COLORS[:BACKGROUND]

COLORS[:DROP_DOWN_TEXT_NEUTRAL] = COLORS[:TEXT]
COLORS[:DROP_DOWN_TEXT_HOT] = COLORS[:TEXT]
COLORS[:DROP_DOWN_TEXT_ACTIVE] = COLORS[:TEXT]

COLORS[:DROP_DOWN_INDICATOR_NEUTRAL] = COLORS[:INDICATOR]
COLORS[:DROP_DOWN_INDICATOR_HOT] = COLORS[:INDICATOR]
COLORS[:DROP_DOWN_INDICATOR_ACTIVE] = COLORS[:INDICATOR]

# Slider
COLORS[:SLIDER_BACKGROUND_NEUTRAL] = COLORS[:BUTTON_BACKGROUND_NEUTRAL]
COLORS[:SLIDER_BACKGROUND_HOT] = COLORS[:BUTTON_BACKGROUND_HOT]
COLORS[:SLIDER_BACKGROUND_ACTIVE] = COLORS[:BUTTON_BACKGROUND_ACTIVE]

COLORS[:SLIDER_BORDER_NEUTRAL] = COLORS[:BORDER]
COLORS[:SLIDER_BORDER_HOT] = COLORS[:BORDER]
COLORS[:SLIDER_BORDER_ACTIVE] = COLORS[:BORDER]

COLORS[:SLIDER_INDICATOR_NEUTRAL] = COLORS[:INDICATOR]
COLORS[:SLIDER_INDICATOR_HOT] = COLORS[:INDICATOR]
COLORS[:SLIDER_INDICATOR_ACTIVE] = COLORS[:INDICATOR]

# Image
COLORS[:IMAGE_BORDER_NEUTRAL] = COLORS[:BORDER]
COLORS[:IMAGE_BORDER_HOT] = COLORS[:BORDER]
COLORS[:IMAGE_BORDER_ACTIVE] = COLORS[:BORDER]
