@enum ColorIndex begin
    COLOR_INDEX_BACKGROUND = 1
    COLOR_INDEX_BORDER
    COLOR_INDEX_TEXT
    COLOR_INDEX_INDICATOR

    # Button
    COLOR_INDEX_BUTTON_BACKGROUND_NEUTRAL
    COLOR_INDEX_BUTTON_BACKGROUND_HOT
    COLOR_INDEX_BUTTON_BACKGROUND_ACTIVE

    COLOR_INDEX_BUTTON_BORDER_NEUTRAL
    COLOR_INDEX_BUTTON_BORDER_HOT
    COLOR_INDEX_BUTTON_BORDER_ACTIVE

    COLOR_INDEX_BUTTON_TEXT_NEUTRAL
    COLOR_INDEX_BUTTON_TEXT_HOT
    COLOR_INDEX_BUTTON_TEXT_ACTIVE

    # TextBox
    COLOR_INDEX_TEXT_BOX_BACKGROUND_NEUTRAL
    COLOR_INDEX_TEXT_BOX_BACKGROUND_HOT
    COLOR_INDEX_TEXT_BOX_BACKGROUND_ACTIVE

    COLOR_INDEX_TEXT_BOX_BORDER_NEUTRAL
    COLOR_INDEX_TEXT_BOX_BORDER_HOT
    COLOR_INDEX_TEXT_BOX_BORDER_ACTIVE

    COLOR_INDEX_TEXT_BOX_TEXT_NEUTRAL
    COLOR_INDEX_TEXT_BOX_TEXT_HOT
    COLOR_INDEX_TEXT_BOX_TEXT_ACTIVE

    # Text
    COLOR_INDEX_TEXT_BACKGROUND_NEUTRAL
    COLOR_INDEX_TEXT_BACKGROUND_HOT
    COLOR_INDEX_TEXT_BACKGROUND_ACTIVE

    COLOR_INDEX_TEXT_BORDER_NEUTRAL
    COLOR_INDEX_TEXT_BORDER_HOT
    COLOR_INDEX_TEXT_BORDER_ACTIVE

    COLOR_INDEX_TEXT_TEXT_NEUTRAL
    COLOR_INDEX_TEXT_TEXT_HOT
    COLOR_INDEX_TEXT_TEXT_ACTIVE

    # CheckBox
    COLOR_INDEX_CHECK_BOX_BACKGROUND_NEUTRAL
    COLOR_INDEX_CHECK_BOX_BACKGROUND_HOT
    COLOR_INDEX_CHECK_BOX_BACKGROUND_ACTIVE

    COLOR_INDEX_CHECK_BOX_BORDER_NEUTRAL
    COLOR_INDEX_CHECK_BOX_BORDER_HOT
    COLOR_INDEX_CHECK_BOX_BORDER_ACTIVE

    COLOR_INDEX_CHECK_BOX_TEXT_NEUTRAL
    COLOR_INDEX_CHECK_BOX_TEXT_HOT
    COLOR_INDEX_CHECK_BOX_TEXT_ACTIVE

    COLOR_INDEX_CHECK_BOX_INDICATOR_NEUTRAL
    COLOR_INDEX_CHECK_BOX_INDICATOR_HOT
    COLOR_INDEX_CHECK_BOX_INDICATOR_ACTIVE

    # RadioButton
    COLOR_INDEX_RADIO_BUTTON_BACKGROUND_NEUTRAL
    COLOR_INDEX_RADIO_BUTTON_BACKGROUND_HOT
    COLOR_INDEX_RADIO_BUTTON_BACKGROUND_ACTIVE

    COLOR_INDEX_RADIO_BUTTON_BORDER_NEUTRAL
    COLOR_INDEX_RADIO_BUTTON_BORDER_HOT
    COLOR_INDEX_RADIO_BUTTON_BORDER_ACTIVE

    COLOR_INDEX_RADIO_BUTTON_TEXT_NEUTRAL
    COLOR_INDEX_RADIO_BUTTON_TEXT_HOT
    COLOR_INDEX_RADIO_BUTTON_TEXT_ACTIVE

    COLOR_INDEX_RADIO_BUTTON_INDICATOR_NEUTRAL
    COLOR_INDEX_RADIO_BUTTON_INDICATOR_HOT
    COLOR_INDEX_RADIO_BUTTON_INDICATOR_ACTIVE

    # DropDown
    COLOR_INDEX_DROP_DOWN_BACKGROUND_NEUTRAL
    COLOR_INDEX_DROP_DOWN_BACKGROUND_HOT
    COLOR_INDEX_DROP_DOWN_BACKGROUND_ACTIVE

    COLOR_INDEX_DROP_DOWN_BORDER_NEUTRAL
    COLOR_INDEX_DROP_DOWN_BORDER_HOT
    COLOR_INDEX_DROP_DOWN_BORDER_ACTIVE

    COLOR_INDEX_DROP_DOWN_TEXT_NEUTRAL
    COLOR_INDEX_DROP_DOWN_TEXT_HOT
    COLOR_INDEX_DROP_DOWN_TEXT_ACTIVE

    COLOR_INDEX_DROP_DOWN_INDICATOR_NEUTRAL
    COLOR_INDEX_DROP_DOWN_INDICATOR_HOT
    COLOR_INDEX_DROP_DOWN_INDICATOR_ACTIVE

    # Slider
    COLOR_INDEX_SLIDER_BACKGROUND_NEUTRAL
    COLOR_INDEX_SLIDER_BACKGROUND_HOT
    COLOR_INDEX_SLIDER_BACKGROUND_ACTIVE

    COLOR_INDEX_SLIDER_BORDER_NEUTRAL
    COLOR_INDEX_SLIDER_BORDER_HOT
    COLOR_INDEX_SLIDER_BORDER_ACTIVE

    COLOR_INDEX_SLIDER_TEXT_NEUTRAL
    COLOR_INDEX_SLIDER_TEXT_HOT
    COLOR_INDEX_SLIDER_TEXT_ACTIVE

    COLOR_INDEX_SLIDER_INDICATOR_NEUTRAL
    COLOR_INDEX_SLIDER_INDICATOR_HOT
    COLOR_INDEX_SLIDER_INDICATOR_ACTIVE

    # Image
    COLOR_INDEX_IMAGE_BORDER_NEUTRAL
    COLOR_INDEX_IMAGE_BORDER_HOT
    COLOR_INDEX_IMAGE_BORDER_ACTIVE
end

const DEFAULT_COLORS = zeros(UInt32, length(instances(ColorIndex)))

DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)] = 0x00cccccc
DEFAULT_COLORS[Integer(COLOR_INDEX_BORDER)] = 0x00000000
DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT)] = 0x00000000
DEFAULT_COLORS[Integer(COLOR_INDEX_INDICATOR)] = 0x00000000

# Button
DEFAULT_COLORS[Integer(COLOR_INDEX_BUTTON_BACKGROUND_NEUTRAL)] = 0x00b0b0b0
DEFAULT_COLORS[Integer(COLOR_INDEX_BUTTON_BACKGROUND_HOT)] = 0x00bfbfbf
DEFAULT_COLORS[Integer(COLOR_INDEX_BUTTON_BACKGROUND_ACTIVE)] = 0x00c0c0c0

DEFAULT_COLORS[Integer(COLOR_INDEX_BUTTON_BORDER_NEUTRAL)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BORDER)]
DEFAULT_COLORS[Integer(COLOR_INDEX_BUTTON_BORDER_HOT)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BORDER)]
DEFAULT_COLORS[Integer(COLOR_INDEX_BUTTON_BORDER_ACTIVE)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BORDER)]

DEFAULT_COLORS[Integer(COLOR_INDEX_BUTTON_TEXT_NEUTRAL)] = DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT)]
DEFAULT_COLORS[Integer(COLOR_INDEX_BUTTON_TEXT_HOT)] = DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT)]
DEFAULT_COLORS[Integer(COLOR_INDEX_BUTTON_TEXT_ACTIVE)] = DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT)]

# TextBox
DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT_BOX_BACKGROUND_NEUTRAL)] = 0x00ffffff
DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT_BOX_BACKGROUND_HOT)] = 0x00ffffff
DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT_BOX_BACKGROUND_ACTIVE)] = 0x00ffffff

DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT_BOX_BORDER_NEUTRAL)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BORDER)]
DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT_BOX_BORDER_HOT)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BORDER)]
DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT_BOX_BORDER_ACTIVE)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BORDER)]

DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT_BOX_TEXT_NEUTRAL)] = DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT)]
DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT_BOX_TEXT_HOT)] = DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT)]
DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT_BOX_TEXT_ACTIVE)] = DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT)]

# Text
DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT_BACKGROUND_NEUTRAL)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]
DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT_BACKGROUND_HOT)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]
DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT_BACKGROUND_ACTIVE)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]

DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT_BORDER_NEUTRAL)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]
DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT_BORDER_HOT)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]
DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT_BORDER_ACTIVE)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]

DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT_TEXT_NEUTRAL)] = DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT)]
DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT_TEXT_HOT)] = DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT)]
DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT_TEXT_ACTIVE)] = DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT)]

# CheckBox
DEFAULT_COLORS[Integer(COLOR_INDEX_CHECK_BOX_BACKGROUND_NEUTRAL)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]
DEFAULT_COLORS[Integer(COLOR_INDEX_CHECK_BOX_BACKGROUND_HOT)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]
DEFAULT_COLORS[Integer(COLOR_INDEX_CHECK_BOX_BACKGROUND_ACTIVE)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]

DEFAULT_COLORS[Integer(COLOR_INDEX_CHECK_BOX_BORDER_NEUTRAL)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]
DEFAULT_COLORS[Integer(COLOR_INDEX_CHECK_BOX_BORDER_HOT)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]
DEFAULT_COLORS[Integer(COLOR_INDEX_CHECK_BOX_BORDER_ACTIVE)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]

DEFAULT_COLORS[Integer(COLOR_INDEX_CHECK_BOX_TEXT_NEUTRAL)] = DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT)]
DEFAULT_COLORS[Integer(COLOR_INDEX_CHECK_BOX_TEXT_HOT)] = DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT)]
DEFAULT_COLORS[Integer(COLOR_INDEX_CHECK_BOX_TEXT_ACTIVE)] = DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT)]

DEFAULT_COLORS[Integer(COLOR_INDEX_CHECK_BOX_INDICATOR_NEUTRAL)] = DEFAULT_COLORS[Integer(COLOR_INDEX_INDICATOR)]
DEFAULT_COLORS[Integer(COLOR_INDEX_CHECK_BOX_INDICATOR_HOT)] = DEFAULT_COLORS[Integer(COLOR_INDEX_INDICATOR)]
DEFAULT_COLORS[Integer(COLOR_INDEX_CHECK_BOX_INDICATOR_ACTIVE)] = DEFAULT_COLORS[Integer(COLOR_INDEX_INDICATOR)]

# RadioButton
DEFAULT_COLORS[Integer(COLOR_INDEX_RADIO_BUTTON_BACKGROUND_NEUTRAL)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]
DEFAULT_COLORS[Integer(COLOR_INDEX_RADIO_BUTTON_BACKGROUND_HOT)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]
DEFAULT_COLORS[Integer(COLOR_INDEX_RADIO_BUTTON_BACKGROUND_ACTIVE)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]

DEFAULT_COLORS[Integer(COLOR_INDEX_RADIO_BUTTON_BORDER_NEUTRAL)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]
DEFAULT_COLORS[Integer(COLOR_INDEX_RADIO_BUTTON_BORDER_HOT)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]
DEFAULT_COLORS[Integer(COLOR_INDEX_RADIO_BUTTON_BORDER_ACTIVE)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]

DEFAULT_COLORS[Integer(COLOR_INDEX_RADIO_BUTTON_TEXT_NEUTRAL)] = DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT)]
DEFAULT_COLORS[Integer(COLOR_INDEX_RADIO_BUTTON_TEXT_HOT)] = DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT)]
DEFAULT_COLORS[Integer(COLOR_INDEX_RADIO_BUTTON_TEXT_ACTIVE)] = DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT)]

DEFAULT_COLORS[Integer(COLOR_INDEX_RADIO_BUTTON_INDICATOR_NEUTRAL)] = DEFAULT_COLORS[Integer(COLOR_INDEX_INDICATOR)]
DEFAULT_COLORS[Integer(COLOR_INDEX_RADIO_BUTTON_INDICATOR_HOT)] = DEFAULT_COLORS[Integer(COLOR_INDEX_INDICATOR)]
DEFAULT_COLORS[Integer(COLOR_INDEX_RADIO_BUTTON_INDICATOR_ACTIVE)] = DEFAULT_COLORS[Integer(COLOR_INDEX_INDICATOR)]

# DropDown
DEFAULT_COLORS[Integer(COLOR_INDEX_DROP_DOWN_BACKGROUND_NEUTRAL)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]
DEFAULT_COLORS[Integer(COLOR_INDEX_DROP_DOWN_BACKGROUND_HOT)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]
DEFAULT_COLORS[Integer(COLOR_INDEX_DROP_DOWN_BACKGROUND_ACTIVE)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]

DEFAULT_COLORS[Integer(COLOR_INDEX_DROP_DOWN_BORDER_NEUTRAL)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]
DEFAULT_COLORS[Integer(COLOR_INDEX_DROP_DOWN_BORDER_HOT)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]
DEFAULT_COLORS[Integer(COLOR_INDEX_DROP_DOWN_BORDER_ACTIVE)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BACKGROUND)]

DEFAULT_COLORS[Integer(COLOR_INDEX_DROP_DOWN_TEXT_NEUTRAL)] = DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT)]
DEFAULT_COLORS[Integer(COLOR_INDEX_DROP_DOWN_TEXT_HOT)] = DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT)]
DEFAULT_COLORS[Integer(COLOR_INDEX_DROP_DOWN_TEXT_ACTIVE)] = DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT)]

DEFAULT_COLORS[Integer(COLOR_INDEX_DROP_DOWN_INDICATOR_NEUTRAL)] = DEFAULT_COLORS[Integer(COLOR_INDEX_INDICATOR)]
DEFAULT_COLORS[Integer(COLOR_INDEX_DROP_DOWN_INDICATOR_HOT)] = DEFAULT_COLORS[Integer(COLOR_INDEX_INDICATOR)]
DEFAULT_COLORS[Integer(COLOR_INDEX_DROP_DOWN_INDICATOR_ACTIVE)] = DEFAULT_COLORS[Integer(COLOR_INDEX_INDICATOR)]

# Slider
DEFAULT_COLORS[Integer(COLOR_INDEX_SLIDER_BACKGROUND_NEUTRAL)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BUTTON_BACKGROUND_NEUTRAL)]
DEFAULT_COLORS[Integer(COLOR_INDEX_SLIDER_BACKGROUND_HOT)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BUTTON_BACKGROUND_HOT)]
DEFAULT_COLORS[Integer(COLOR_INDEX_SLIDER_BACKGROUND_ACTIVE)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BUTTON_BACKGROUND_ACTIVE)]

DEFAULT_COLORS[Integer(COLOR_INDEX_SLIDER_BORDER_NEUTRAL)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BORDER)]
DEFAULT_COLORS[Integer(COLOR_INDEX_SLIDER_BORDER_HOT)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BORDER)]
DEFAULT_COLORS[Integer(COLOR_INDEX_SLIDER_BORDER_ACTIVE)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BORDER)]

DEFAULT_COLORS[Integer(COLOR_INDEX_SLIDER_TEXT_NEUTRAL)] = DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT)]
DEFAULT_COLORS[Integer(COLOR_INDEX_SLIDER_TEXT_HOT)] = DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT)]
DEFAULT_COLORS[Integer(COLOR_INDEX_SLIDER_TEXT_ACTIVE)] = DEFAULT_COLORS[Integer(COLOR_INDEX_TEXT)]

DEFAULT_COLORS[Integer(COLOR_INDEX_SLIDER_INDICATOR_NEUTRAL)] = 0x007a7a7a
DEFAULT_COLORS[Integer(COLOR_INDEX_SLIDER_INDICATOR_HOT)] = 0x007a7a7a
DEFAULT_COLORS[Integer(COLOR_INDEX_SLIDER_INDICATOR_ACTIVE)] = 0x007a7a7a

# Image
DEFAULT_COLORS[Integer(COLOR_INDEX_IMAGE_BORDER_NEUTRAL)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BORDER)]
DEFAULT_COLORS[Integer(COLOR_INDEX_IMAGE_BORDER_HOT)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BORDER)]
DEFAULT_COLORS[Integer(COLOR_INDEX_IMAGE_BORDER_ACTIVE)] = DEFAULT_COLORS[Integer(COLOR_INDEX_BORDER)]
