abstract type AbstractContextualColor end

struct ContextualColor{T} <: AbstractContextualColor
    neutral_color::T
    hot_color::T
    active_color::T
end

# default colors
const COLOR_DEFAULT_BACKGROUND = ContextualColor(0x00cccccc, 0x00cccccc, 0x00cccccc)
const COLOR_DEFAULT_BORDER = ContextualColor(0x00000000, 0x00000000, 0x00000000)
const COLOR_DEFAULT_TEXT = ContextualColor(0x00000000, 0x00000000, 0x00000000)
const COLOR_DEFAULT_INDICATOR = ContextualColor(0x00000000, 0x00000000, 0x00000000)

# Button
const COLOR_BUTTON_BACKGROUND = ContextualColor(0x00b0b0b0, 0x00bfbfbf, 0x00c0c0c0)
const COLOR_BUTTON_BORDER = COLOR_DEFAULT_BORDER
const COLOR_BUTTON_TEXT = COLOR_DEFAULT_TEXT

# TextBox
const COLOR_TEXT_BOX_BACKGROUND = ContextualColor(0x00ffffff, 0x00ffffff, 0x00ffffff)
const COLOR_TEXT_BOX_BORDER = COLOR_DEFAULT_BORDER
const COLOR_TEXT_BOX_TEXT = COLOR_DEFAULT_TEXT

# Text
const COLOR_TEXT_BACKGROUND = COLOR_DEFAULT_BACKGROUND
const COLOR_TEXT_BORDER = COLOR_DEFAULT_BACKGROUND
const COLOR_TEXT_TEXT = COLOR_DEFAULT_TEXT

# CheckBox
const COLOR_CHECK_BOX_BACKGROUND = COLOR_DEFAULT_BACKGROUND
const COLOR_CHECK_BOX_BORDER = COLOR_DEFAULT_BACKGROUND
const COLOR_CHECK_BOX_TEXT = COLOR_DEFAULT_TEXT
const COLOR_CHECK_BOX_INDICATOR = COLOR_DEFAULT_INDICATOR

# RadioButton
const COLOR_RADIO_BUTTON_BACKGROUND = COLOR_DEFAULT_BACKGROUND
const COLOR_RADIO_BUTTON_BORDER = COLOR_DEFAULT_BACKGROUND
const COLOR_RADIO_BUTTON_TEXT = COLOR_DEFAULT_TEXT
const COLOR_RADIO_BUTTON_INDICATOR = COLOR_DEFAULT_INDICATOR

# DropDown
const COLOR_DROP_DOWN_BACKGROUND = COLOR_DEFAULT_BACKGROUND
const COLOR_DROP_DOWN_BORDER = COLOR_DEFAULT_BACKGROUND
const COLOR_DROP_DOWN_TEXT = COLOR_DEFAULT_TEXT
const COLOR_DROP_DOWN_INDICATOR = COLOR_DEFAULT_INDICATOR

# Slider
const COLOR_SLIDER_BACKGROUND = ContextualColor(0x00b0b0b0, 0x00b7b7b7, 0x00c0c0c0)
const COLOR_SLIDER_BORDER = COLOR_DEFAULT_BORDER
const COLOR_SLIDER_INDICATOR = COLOR_DEFAULT_INDICATOR

# Image
const COLOR_IMAGE_BORDER = COLOR_DEFAULT_BORDER

get_colors(widget_type::Button) = (COLOR_BUTTON_BACKGROUND, COLOR_BUTTON_BORDER, COLOR_BUTTON_TEXT)
get_colors(widget_type::TextBox) = (COLOR_TEXT_BOX_BACKGROUND, COLOR_TEXT_BOX_BORDER, COLOR_TEXT_BOX_TEXT)
get_colors(widget_type::Text) = (COLOR_TEXT_BACKGROUND, COLOR_TEXT_BORDER, COLOR_TEXT_TEXT)
get_colors(widget_type::CheckBox) = (COLOR_CHECK_BOX_BACKGROUND, COLOR_CHECK_BOX_BORDER, COLOR_CHECK_BOX_TEXT, COLOR_CHECK_BOX_INDICATOR)
get_colors(widget_type::RadioButton) = (COLOR_RADIO_BUTTON_BACKGROUND, COLOR_RADIO_BUTTON_BORDER, COLOR_RADIO_BUTTON_TEXT, COLOR_RADIO_BUTTON_INDICATOR)
get_colors(widget_type::DropDown) = (COLOR_DROP_DOWN_BACKGROUND, COLOR_DROP_DOWN_BORDER, COLOR_DROP_DOWN_TEXT, COLOR_DROP_DOWN_INDICATOR)
get_colors(widget_type::Slider) = (COLOR_SLIDER_BACKGROUND, COLOR_SLIDER_BORDER, COLOR_SLIDER_INDICATOR)
get_colors(widget_type::Image) = (COLOR_IMAGE_BORDER,)
