struct ContextualColor{T}
    neutral_color::T
    hot_color::T
    active_color::T
end

# default colors
COLOR_DEFAULT_BACKGROUND = ContextualColor(0x00cccccc, 0x00cccccc, 0x00cccccc)
COLOR_DEFAULT_BORDER = ContextualColor(0x00000000, 0x00000000, 0x00000000)
COLOR_DEFAULT_TEXT = ContextualColor(0x00000000, 0x00000000, 0x00000000)
COLOR_DEFAULT_INDICATOR = ContextualColor(0x00000000, 0x00000000, 0x00000000)

# Button
COLOR_BUTTON_BACKGROUND = ContextualColor(0x00b0b0b0, 0x00bfbfbf, 0x00c0c0c0)
COLOR_BUTTON_BORDER = COLOR_DEFAULT_BORDER
COLOR_BUTTON_TEXT = COLOR_DEFAULT_TEXT

# TextBox
COLOR_TEXT_BOX_BACKGROUND = ContextualColor(0x00ffffff, 0x00ffffff, 0x00ffffff)
COLOR_TEXT_BOX_BORDER = COLOR_DEFAULT_BORDER
COLOR_TEXT_BOX_TEXT = COLOR_DEFAULT_TEXT

# Text
COLOR_TEXT_BACKGROUND = COLOR_DEFAULT_BACKGROUND
COLOR_TEXT_BORDER = COLOR_DEFAULT_BACKGROUND
COLOR_TEXT_TEXT = COLOR_DEFAULT_TEXT

# CheckBox
COLOR_CHECK_BOX_BACKGROUND = COLOR_DEFAULT_BACKGROUND
COLOR_CHECK_BOX_BORDER = COLOR_DEFAULT_BACKGROUND
COLOR_CHECK_BOX_TEXT = COLOR_DEFAULT_TEXT
COLOR_CHECK_BOX_INDICATOR = COLOR_DEFAULT_INDICATOR

# RadioButton
COLOR_RADIO_BUTTON_BACKGROUND = COLOR_DEFAULT_BACKGROUND
COLOR_RADIO_BUTTON_BORDER = COLOR_DEFAULT_BACKGROUND
COLOR_RADIO_BUTTON_TEXT = COLOR_DEFAULT_TEXT
COLOR_RADIO_BUTTON_INDICATOR = COLOR_DEFAULT_INDICATOR

# DropDown
COLOR_DROP_DOWN_BACKGROUND = COLOR_DEFAULT_BACKGROUND
COLOR_DROP_DOWN_BORDER = COLOR_DEFAULT_BACKGROUND
COLOR_DROP_DOWN_TEXT = COLOR_DEFAULT_TEXT
COLOR_DROP_DOWN_INDICATOR = COLOR_DEFAULT_INDICATOR

# Slider
COLOR_SLIDER_BACKGROUND = ContextualColor(0x00b0b0b0, 0x00b7b7b7, 0x00c0c0c0)
COLOR_SLIDER_BORDER = COLOR_DEFAULT_BORDER
COLOR_SLIDER_INDICATOR = COLOR_DEFAULT_INDICATOR

# Image
COLOR_IMAGE_BORDER = COLOR_DEFAULT_BORDER
